numactl -N 0 -l /home/zhou822/gfe_driver_sigmod2025/build/gfe_driver -G /ssd_root/zhou822/graph_source/yahoo-song/out.yahoo-song.el -u -l sortledton.4 -w 72 --block_size 512
numactl -N 0 -l /home/zhou822/gfe_driver_sigmod2025/build/gfe_driver -G /ssd_root/zhou822/graph_source/yahoo-song/out.yahoo-song.el -u -l sortledton.4 -w 64 --block_size 512
numactl -N 0 -l /home/zhou822/gfe_driver_sigmod2025/build/gfe_driver -G /ssd_root/zhou822/graph_source/yahoo-song/out.yahoo-song.el -u -l sortledton.4 -w 56 --block_size 512
numactl -N 0 -l /home/zhou822/gfe_driver_sigmod2025/build/gfe_driver -G /ssd_root/zhou822/graph_source/yahoo-song/out.yahoo-song.el -u -l sortledton.4 -w 48 --block_size 512
numactl -N 0 -l /home/zhou822/gfe_driver_sigmod2025/build/gfe_driver -G /ssd_root/zhou822/graph_source/yahoo-song/out.yahoo-song.el -u -l sortledton.4 -w 40 --block_size 512
numactl -N 0 -l /home/zhou822/gfe_driver_sigmod2025/build/gfe_driver -G /ssd_root/zhou822/graph_source/yahoo-song/out.yahoo-song.el -u -l sortledton.4 -w 32 --block_size 512
numactl -N 0 -l /home/zhou822/gfe_driver_sigmod2025/build/gfe_driver -G /ssd_root/zhou822/graph_source/yahoo-song/out.yahoo-song.el -u -l sortledton.4 -w 24 --block_size 512
numactl -N 0 -l /home/zhou822/gfe_driver_sigmod2025/build/gfe_driver -G /ssd_root/zhou822/graph_source/yahoo-song/out.yahoo-song.el -u -l sortledton.4 -w 16 --block_size 512
numactl -N 0 -l /home/zhou822/gfe_driver_sigmod2025/build/gfe_driver -G /ssd_root/zhou822/graph_source/yahoo-song/out.yahoo-song.el -u -l sortledton.4 -w 8  --block_size 512
numactl -N 0 -l /home/zhou822/gfe_driver_sigmod2025/build/gfe_driver -G /ssd_root/zhou822/graph_source/yahoo-song/out.yahoo-song.el -u -l sortledton.4 -w 4  --block_size 512